version: '3'

services:
  client:
    build: .
    ports:
      - "3000:3000"
    networks:
      - ecom_api_my_network
  nginx2:
    build: ./nginx2
    volumes:
      - static:/static
    ports:
      - "80:80"
    networks:
      - ecom_api_my_network
volumes:
  static:


networks:
  ecom_api_my_network:
    external: true
